# This workflow will automate the process of building and testing Node.js projects, and deploys the project to GitHub  upon successful completion of the tests

name: Node.js CI/CD

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Commit built artifacts
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout -b deploy  # Create or switch to a 'deploy' branch
          git add .  # Add all changes (including built artifacts)
          git commit -m "Deploy latest build from GitHub Actions"
          git push --quiet --set-upstream origin deploy  # Push changes to the 'deploy' branch

      - name: Set success flag
        id: set-success-flag
        run: echo "::set-output name=success::true"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy built artifacts
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git fetch origin deploy:${{ github.sha }}
          git checkout deploy
          git merge ${{ github.sha }}
          git push --quiet origin deploy  # Push changes to the 'deploy' branch

      - name: Clean up
        run: |
          git checkout development
          git branch -D deploy  # Delete the 'deploy' branch after deployment