# This workflow will automate the process of building and testing Node.js projects, and deploys the project to GitHub  upon successful completion of the tests

name: Backend CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Set Success Output
        if: success()
        run: echo "success=true" >> $GITHUB_ENV

  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to Production
        uses: everlytic/branch-merge@1.1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_ref: ${{ github.ref }}
          target_branch: 'production'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
