# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
   branches: [ "main" ]
  pull_request:
   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        
    steps: 
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - name: Set Success Output
      if: success()
      run: echo "success=true" >> $GITHUB_OUTPUT
 
  release:
   needs: build
   runs-on: ubuntu-latest
   if: ${{[needs.build](http://needs.build).result == 'success'}}

   steps:
     - uses: actions/checkout@v3
     - uses: everlytic/branch-merge@1.1.5
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         source_ref: ${{ github.ref }}
         target_branch: 'stage'
         commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'  
    
    
    
   
          

 

